main_app/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library_blog.urls')),
    path('', include('age_rest_books.urls')),
    path('', include('basket.urls')),
    path('', include('parser_app.urls')),
    path('', include('users.urls')),
    path('recipes/', include('recipes.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

month_4_hw-master/main_app/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library_blog.urls')),
    path('', include('age_rest_books.urls')),
    path('', include('basket.urls')),
    path('', include('parser_app.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.RegistrationView.as_view(), name='register'),
    path('login/', views.AuthLoginView.as_view(), name='login'),
    path('logout/', views.AuthLogoutView.as_view(), name='logout'),
    path('user_list/', views.UserListView.as_view(), name='user_list'),
]

recipes/models.py
from django.db import models

class Recipe(models.Model):
    title = models.CharField(max_length=200, verbose_name="Название рецепта")
    description = models.TextField(verbose_name="Описание рецепта")

    def __str__(self):
        return self.title


class Ingredient(models.Model):
    UNITS = [
        ('г', 'Граммы'),
        ('кг', 'Килограммы'),
        ('мл', 'Миллилитры'),
        ('л', 'Литры'),
        ('шт', 'Штуки'),
    ]
    name = models.CharField(max_length=100, verbose_name="Название ингредиента")
    quantity = models.FloatField(verbose_name="Количество")
    unit = models.CharField(max_length=10, choices=UNITS, verbose_name="Единица измерения")
    recipe = models.ForeignKey(Recipe, related_name='ingredients', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} - {self.quantity} {self.unit}"

templates/components/footer.html
<footer>
    © 2024 Ваш Сайт:
    <a class="text-reset fw-bold" href="#" style="color: yellow;">ВашСайт.com</a>
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>
</html>

templates/components/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Geek Book</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="shortcut icon"
          href="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9RaqWhNrT68sVwQFo4ZAs1VRsUZImppmaqg&s">
    <link rel="stylesheet" href="{% static 'main_page/book_list.css' %}">
</head>
<body>

<!-- Навигационная панель -->
<nav class="navbar navbar-expand-lg bg-body-tertiary fixed-top"
     style="background: linear-gradient(to right, #1a1919, #100f0f);">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <img src="https://lh5.googleusercontent.com/yzWtzlXIlHfLjcFkr0S7UgmoX9HFoJ6VRszWZyEt-G85Gl5ID_XxoLX6Ji6E223S-EU2UUt2Y89uOwkm0tr8KkLQbM4Su17ln5HVBLaLHfxFIqm4DDpwmzPhfeAg1mja2Xdz7JkCvJqbpoEOT0CX8Cg"
                 alt="Logo" style="width: 40px; height: 40px;">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Переключатель навигации">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#" style="color: yellow;">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'all_books' %}" style="color: yellow;">Хэш теги</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false" style="color: yellow;">
                        Basket
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'createBasket' %}">Добавить корзину</a></li>
                        <li><a class="dropdown-item" href="{% url 'basketList' %}">Список корзин</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link enable" href="{% url 'users:register' %}" style="color: yellow;">Регистрация</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link enable" href="{% url 'recipes:recipe_list' %}" style="color: yellow;">Рецепты</a>
                </li>                
                <li class="nav-item">
                    <a class="nav-link enable" href="{% url 'kinoogo_list' %}" style="color: yellow;">Другие книги</a>
                </li>
            </ul>
             <form action="{% url 'search' %}" method="GET" class="d-flex" role="search">
                <input class="form-control me-2"type="text" name="q" type="search" placeholder="Поиск" aria-label="Поиск">
                <button class="btn btn-outline-success" type="submit" style="color: yellow; border-color: yellow;">
                    Поиск
                </button>
            </form>
        </div>
    </div>
</nav>